src/editors/data/api.js

Just as the title says-- block key comes in encoded, don't encode it again. Will require a version bump in course authoring upon merge/release

fix: dont encode with uri twice

---

package-lock.json
src/editors/containers/TextEditor/components/SelectImageModal/Gallery.jsx
src/editors/containers/TextEditor/components/SelectImageModal/Gallery.test.jsx
src/editors/containers/TextEditor/components/SelectImageModal/__snapshots__/Gallery.test.jsx.snap
src/editors/containers/TextEditor/components/SelectImageModal/hooks.js
src/editors/containers/TextEditor/components/SelectImageModal/messages.js

Added 2 labels for when gallery is empty:
1. When no images are returned from backend.
2. When search returns 0 results.
This does not match the mockups in figma and is more of a quick temporary solution.

Feat: empty gallery

---

src/editors/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/components/EditorFooter/index.jsx
src/editors/containers/TextEditor/TextEditor.jsx
src/editors/containers/TextEditor/__snapshots__/TextEditor.test.jsx.snap
src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx

Screenshots show how footer is now locked to bottom of page, and that text editor content scrolls, and that this works on resize of page.

fix: update texteditor spacing

---

src/editors/components/EditorHeader/__snapshots__/index.test.jsx.snap
src/editors/components/EditorHeader/hooks.js
src/editors/components/EditorHeader/hooks.test.js
src/editors/components/EditorHeader/index.jsx
src/editors/components/EditorHeader/index.test.jsx

I decided to change the enter-key logic to be the same as tab-key, which wasn't working as intended. It turns out that the editorRef wasn't getting passed down properly to HeaderTitle.jsx.

fix: saving block title

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptsWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/duration.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/duration.test.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/handlers.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/handlers.test.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/hooks.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/hooks.test.js
src/editors/containers/VideoEditor/index.jsx
src/editors/data/constants/video.js
src/editors/data/redux/video/reducer.js
src/editors/data/services/cms/mockVideoData.js

Adds implementations for the duration and video source hooks, while, more importantly, providing a tested hook framework for the remainder of the collapsible widgets.
JIRA:
[TNL-9823](https://openedx.atlassian.net/browse/TNL-9823)
[TNL-9722](https://openedx.atlassian.net/browse/TNL-9772)

feat: video skeleton hooks

---

.github/workflows/lockfileversion-check.yml

lockfileVersion for the package-lock.json generated by NPM6 was 1 but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is 2. So here we're going to check the lockfileVersion in package-lock.json

feat: Add package-lock file version check

---

src/editors/containers/TextEditor/pluginConfig.js
src/editors/data/constants/tinyMCE.js

This PR adds the missing text underline button and functionality to the Text Editor toolbar. To add the functionality, a new parameter was added to the tinyMCE configuration. No new tests required since toolbar tests are already present and cover the new button.
Jira Ticket: [TNL-10003](https://2u-internal.atlassian.net/browse/TNL-10003?atlOrigin=eyJpIjoiZGU2MTNmZDNhNzdkNDZlOWJjZDAzMGU3MWZmYzY1ZjQiLCJwIjoiaiJ9)

fix: added underline option to toolbar. TNL-10003

---

src/editors/containers/TextEditor/components/ErrorAlerts/__snapshots__/FetchErrorAlert.test.jsx.snap
src/editors/containers/TextEditor/components/ErrorAlerts/__snapshots__/UploadErrorAlert.test.jsx.snap
src/editors/containers/TextEditor/components/ImageUploadModal.jsx
src/editors/containers/TextEditor/components/SelectImageModal/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/components/SelectImageModal/hooks.js
src/editors/containers/TextEditor/components/SelectImageModal/hooks.test.js
src/editors/containers/TextEditor/components/SelectImageModal/index.jsx
src/editors/containers/TextEditor/components/SelectImageModal/index.test.jsx
src/editors/containers/TextEditor/components/SelectImageModal/messages.js
src/editors/containers/TextEditor/components/__snapshots__/ImageUploadModal.test.jsx.snap
src/editors/data/redux/thunkActions/app.js
src/editors/data/redux/thunkActions/requests.js

This PR adds the ability to prevent uploading an image larger than 10 MB and a loading spinner while the image is loading. I changed the error message users see when the upload fails due to file size. The new alert lets users know that the file size it too large instead of a vague error message. New tests added to check the function `checkValidFileSize`'s return value and when it is called. Also made small updates to existing tests.
Jira Ticket: [TNL-9939](https://2u-internal.atlassian.net/browse/TNL-9939)

feat: Prevent image uploads larger than 10 MB and add spinner

---

src/editors/containers/TextEditor/components/ImageSettingsModal/DimensionControls.jsx
src/editors/containers/TextEditor/components/ImageSettingsModal/hooks.js
src/editors/containers/TextEditor/components/ImageSettingsModal/index.jsx

This PR fixes the persistence issues with altText and decorative details when editing an image. To fix the persistence, a call to update the values when loading the image was missing. Previously there was only a call to update the image dimension fields. 
Jira Ticket: [TNL-9953](https://2u-internal.atlassian.net/browse/TNL-9953)

feat: add altText and isDecorative persistence for image editing

---

src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx
src/editors/data/constants/tinyMCE.js

This change addresses https://2u-internal.atlassian.net/browse/TNL-9971
1. Focus is kept when pressing the Code Block button.
2. Undo and Redo states keep track of when Code Block button is pressed. Minor issue with this below.
Bonus: Code Block button will be active when caret is at Code Block text.
There is a small issue with undo/redo with Code Block. The caret may end up at unexpected positions when pressing undo/redo with Code Block changes to the tinyMCE text.

Feat  updates to code block button

---

src/editors/containers/TextEditor/hooks.js
src/editors/data/constants/tinyMCEStyles.js

This PR addresses the font discrepancy in studio and the new editor. The editor was set to use the default styling, so the font that is used in studio was never set. The editor is now set to use the same font as studio with the `content_style` attribute.
Jira Ticket [TNL-10057](https://2u-internal.atlassian.net/browse/TNL-10057)

feat: update editor text to match studio styling

---

src/editors/containers/TextEditor/hooks.js

This PR address the console errors for `skin.css`. The changes add missing boolean attributes in the components init function. No new test required.
JIRA Ticket: [TNL-9974](https://2u-internal.atlassian.net/browse/TNL-9974)

feat: resolve console errors regarding skin.css

---

src/editors/containers/TextEditor/components/ImageSettingsModal/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/components/ImageSettingsModal/index.jsx
src/editors/containers/TextEditor/components/ImageSettingsModal/index.test.jsx

https://2u-internal.atlassian.net/browse/TNL-9973
When editing existing images, the UI fails to generate properly on images with broken links. This is because we are running the load logic on the image's onLoad event. This causes issues down the line with saving the dimensions to a broken image.

feat: run onImgLoad even on broken images

---

src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/components/ImageUploadModal.jsx
src/editors/containers/TextEditor/components/SelectImageModal/hooks.js
src/editors/containers/TextEditor/components/SelectImageModal/hooks.test.js
src/editors/containers/TextEditor/components/SelectImageModal/index.jsx
src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx
src/editors/containers/TextEditor/index.jsx
src/editors/containers/TextEditor/index.test.jsx
src/editors/containers/TextEditor/pluginConfig.js
src/editors/data/redux/app/reducer.js
src/editors/data/redux/app/reducer.test.js
src/editors/data/redux/app/selectors.js
src/editors/data/redux/app/selectors.test.js
src/editors/data/redux/thunkActions/app.js
src/editors/data/redux/thunkActions/app.test.js

This PR changes `/static/` links to `/assets/` links. This fixes the broken links in the editor view. The links are automatically replaced when the source code is saved and the user is navigated back to the main body of the editor. Updated tests to reflect the new way that `fetchImages` is called and how images are passed between components.
Linked PR:  edx-platform [PR #30886](https://github.com/openedx/edx-platform/pull/30886)
Jira Ticket: [TNL-10077](https://2u-internal.atlassian.net/browse/TNL-10077)

feat: change static url to asset url in editor

---

src/editors/containers/TextEditor/components/CodeEditor/index.jsx

This PR address the horizontal scroll when editing raw html. Previously the user would manually have to enter for new lines or the line would stretch on forever. This makes it difficult to read the html. Now the text will automatically wrap the line when it hits the edge of the container.
JIRA Ticket: [TNL-10099](https://2u-internal.atlassian.net/browse/TNL-10099)

feat: add codeMirror lineWrapping extension

---

src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx
src/editors/containers/TextEditor/index.jsx
src/editors/containers/TextEditor/index.test.jsx
src/editors/containers/TextEditor/pluginConfig.js
src/editors/data/redux/app/selectors.js
src/editors/data/redux/app/selectors.test.js

This PR removes the functionality of images in the text editor for content libraries, but retains the functionality for course blocks. Updated test to include the check for if the editor is editing a library block.
JIRA Ticket: [TNL-9958](https://2u-internal.atlassian.net/browse/TNL-9958)

feat: remove the ability to use image tools for content libraries

---

src/editors/data/constants/tinyMCEStyles.js

This PR adds the missing CSS from tinyMCE that allows for image resizing by dragging. Solution based on [tinymce-react Issue 56](https://github.com/tinymce/tinymce-react/issues/56).
JIRA ticket: [TNL-10084](https://2u-internal.atlassian.net/browse/TNL-10084)

feat: add tinyMCE functionality for drag resizing of images

---

src/editors/containers/EditorContainer/hooks.js
src/editors/containers/EditorContainer/hooks.test.jsx
src/editors/containers/TextEditor/components/ImageUploadModal.jsx
src/editors/containers/TextEditor/components/ImageUploadModal.test.jsx
src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx
src/editors/data/redux/app/selectors.test.js

This PR fixes the image src's being absolute URLs instead of relative URLs. This PR also adds functionality to convert all image src's to `/static/` links to match expected URL format in studio for course re-runs and export/import functionality. New tests added to test the URL change and old tests updated to match variable changes.
JIRA Ticket: [TNL-10104](https://2u-internal.atlassian.net/browse/TNL-10104)

feat: change image absolute urls to relative urls

---

src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/components/RawEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/components/RawEditor/index.jsx
src/editors/containers/TextEditor/components/RawEditor/index.test.jsx
src/editors/containers/TextEditor/index.jsx
src/editors/containers/TextEditor/index.test.jsx

As sometimes the html components are rendered downstream before the block is loaded, we need to handle the case of no block value being provided to the raw editor at the time of first render. Subsequent thunk actions will trigger re-renders to display the block.

fix: intermittent raw loading error

---

src/editors/containers/TextEditor/components/SelectImageModal/__snapshots__/FileInput.test.jsx.snap
src/editors/containers/TextEditor/components/SelectImageModal/utils.js

This PR allows .ico images to be uploaded in the text editor. File input snapshot was updated to include new allowed file type and no new tests were added.
JIRA Ticket: [TNL-9952](https://2u-internal.atlassian.net/browse/TNL-9952)

feat: allow .ico image file types

---

src/editors/containers/TextEditor/components/ImageUploadModal.jsx
src/editors/containers/TextEditor/components/ImageUploadModal.test.jsx

This PR fixes the bug that made image link undefined in the text editor. Previously the `src` value for was changed from an absolute url to a relative url. Not all of the name references and functionality were updated with change. The change has been reverted and replaced with getting the relative path substring from the absolute url.

feat: revert  selection.url  change and replaced with getting the relative path substring from the absolute url

---

src/editors/containers/TextEditor/hooks.js

This PR fixes bug in main that breaks saving text editor. While updating the text editor to use all assets, not just images, the variables types were not updated for when getting the static url from all the assets.

fix: text editor save to use assets array instead of object

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.test.jsx

Content libraries do not have asset pages, so the ability to upload handouts is not possible. As a result, the handout widget is not displayed if it is a library block.

feat: remove handout widget for content libraries

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.jsx

Add conditional that checks if the block is from a content library. Content libraries do not host their own videos. Therefore any edx-hosted video present in a content library originates from another course. When trying to upload a new thumbnail it errors out because it is trying to find the video in the library. To prevent this error, the thumbnail widget is not visible to users in content libraries.

feat: remove thumbnail widget from content libraries

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/messages.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/DurationWidget.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/index.jsx
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

This PR address the following UI bugs
- When scrolling down, "Settings" will overlap with Video Title. Also left and right margins are different, assuming they should align with the title and close button.
- There is a spacing issue on the placement of the handout filename when one is selected.
- Collapsed view of widget should say "None" if no thumbnail is present
- Collapsed view of widget should say image name (do we want this since it won’t have the original name of the image? it will essentially be by the video id) 
- Remove “Starts at …” from expanded view of widget, but keep in collapsed

fix: non-blocking UI bugs for video settings

---

src/editors/data/redux/thunkActions/video.js

JIRA Ticket: [TNL-10227](https://2u-internal.atlassian.net/browse/TNL-10227)
This PR addresses the error message "an unexpected error occurred. Please click the button below to refresh the page.". When course is created with xml, it does not define `html5Sources` as an empty list. This PR updates the conditional that sets `fallbackVideos` to `['', '']` so that it also check for undefined values.

fix: length error on undefined fallback videos

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseBlurb.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseBlurb.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDetails.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseSelector.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/Transcript.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/Transcript.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap

JIRA Tickets: [TNL-10241](https://2u-internal.atlassian.net/browse/TNL-10241), [TNL-10248](https://2u-internal.atlassian.net/browse/TNL-10248), and [TNL-10251](https://2u-internal.atlassian.net/browse/TNL-10251)
This PR sets all fonts and icons to `primary-500`. All text except link buttons and checkboxes use the `.x-small` css class. Link buttons and checkboxes use the `.small` css. class and `sm` for the size attribute. The info and delete icons are aligned relative to their containers.

fix: font/icon size and color

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx

This solves the first half of https://2u-internal.atlassian.net/browse/TNL-10238 "All add/upload links should be left aligned." However, we still need to address "update the color for the upload handout icon to match the other links" in https://github.com/openedx/paragon/issues/1816

feat: left align widget "add" buttons

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/hooks.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/hooks.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/messages.js
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

JIRA Tickets: [TNL-10256](https://2u-internal.atlassian.net/browse/TNL-10256), [TNL-10247](https://2u-internal.atlassian.net/browse/TNL-10247), and [TNL-10252](https://2u-internal.atlassian.net/browse/TNL-10252)
Previously, when a thumbnail was deleted from a video it would delete in the video settings but had no impact on the xblock. This allowed the previous thumbnail to persist in the player and Video Upload page. This PR saves a black canvas as an image when the current thumbnail is deleted. The user does not see the black canvas, but it is stored to the xblock so that the previous thumbnail is not longer seen.

feat: add black canvas when current thumbnail is deleted

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx

This PR removes the condition that prevents "View License Details" hyperlink when showing course level license.
JIRA Ticket: [TNL-10271](https://2u-internal.atlassian.net/browse/TNL-10271)

feat: show view license link at all levels

---

src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/index.jsx
src/editors/containers/EditorContainer/index.jsx
src/editors/containers/TextEditor/pluginConfig.js

https://2u-internal.atlassian.net/browse/TNL-10234
This change will keep header above the content when user scrolls down. TinyMCE sticky toolbar in the text editor is kept at the appropriate height.

feat: header overlap content when scrolling down

---

src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

https://2u-internal.atlassian.net/browse/TNL-10281
Video Settings run into an error when opening while preferred language is not english. This is because we are expecting english when parsing transcript files. This change aims to parse transcript files regardless of the user's preferred language.

feat: parseTranscript to work with all languages

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/messages.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/hooks.js
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js
src/editors/data/redux/video/reducer.js
src/editors/data/redux/video/selectors.js
src/editors/data/services/cms/api.js
src/editors/data/services/cms/api.test.js

JIRA Ticket: [TNL-10274](https://2u-internal.atlassian.net/browse/TNL-10274)
This PR separates the Video ID or URL field into separate fields. If a user happens to have both saved to the block it will separate them into the respective fields. Additionally when editing, if a user tries to but a video ID in the URL field is will adjust it to be in the correct field and vice versa.

feat: separate video id and url fields into two

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx

This is a follow on[ PR to separating video ID and video URL into two fields](https://github.com/openedx/frontend-lib-content-components/pull/164). In the previous implementation and user could clear one of the fields and it would end up clearing both. Now only the expected field is cleared onBlur.

fix: add check if field is cleared

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
src/editors/containers/ProblemEditor/index.jsx
src/editors/data/redux/thunkActions/problem.js
src/editors/data/redux/thunkActions/problem.test.js
www/package-lock.json

So this PR is slated to complete
https://2u-internal.atlassian.net/browse/TNL-10260
Notes: I made it so there is only one advanced problem type (ADVANCED) after selection, and the advanceProblemTypeKey simply tracks which template to use.
https://2u-internal.atlassian.net/browse/TNL-10261
Notes: TODO: add confirmation dialog.
https://2u-internal.atlassian.net/browse/TNL-10262
Notes: do we think this approach makes sense? Does it make development of the parser more opaque?
I used atomic commits, and they were completed in that order, hopefully that makes things easy :)

Feat:  raw editor ingress and egress logic

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswersContainer.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeCard.test.jsx.snap
src/editors/containers/ProblemEditor/hooks.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/problem/reducers.test.js
src/editors/data/redux/problem/selectors.js
src/editors/data/redux/problem/selectors.test.js

JIRA Ticket: [TNL-10286](https://2u-internal.atlassian.net/browse/TNL-10286)
This ticket resolves the bug that allowed multiple answers to be selected when switching between multi-select problem types and single select problem types. Now when a user switches from a multi-select problem to a single select problem with multiple selected answers, all the answers will be deselected. If only one answer is selected, the answer is persisted.

feat: unselect multiple choices type multi->single

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ShowAnswerCard.test.jsx.snap

JIRA Ticket: [TNL-10326](https://2u-internal.atlassian.net/browse/TNL-10326)
This PR sets the "Set a default value in advanced settings" link to `<studiourl>/settings/advanced/<courseID>`. Previously the link was set to `#` so it was opening the problem editor page, but in a different tab.

fix: change # destination to advance settings url

---

.github/workflows/release.yml

I saw that the release CI https://github.com/openedx/frontend-lib-content-components/actions/runs/3897027405/jobs/6654318273 was failing the release on `[semantic-release]: node version >=18 is required. Found v16.19.0.`
from https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0 we learn that ` node v18 is now the minimum required version of node. `
The version of semantic-release that runs in a repo is usually based on the relevant Github Acton workflow file for the release, defined in the repo itself.
I am pinning that version to 19.0.5 until the next node upgrade, as it seems we recently upgrade to node 16.

build: pin semantic release to unblock pipeline

---

src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
src/editors/data/constants/advancedOlxTemplates/circuitschematic.js
src/editors/data/constants/advancedOlxTemplates/customgrader.js
src/editors/data/constants/advancedOlxTemplates/drag_and_drop.js
src/editors/data/constants/advancedOlxTemplates/formularesponse.js
src/editors/data/constants/advancedOlxTemplates/imageresponse.js
src/editors/data/constants/advancedOlxTemplates/jsinput_response.js
src/editors/data/constants/advancedOlxTemplates/problem_with_hint.js

As I was writing the select type egress, I fixed a bug where the wrong rawolx object was being loaded in for basic problem types. this fixes it for advanced ones as well.

Fix: advanced problem template reference

---

src/editors/containers/ProblemEditor/components/SelectTypeModal/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/content/Preview.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/AdvanceTypeSelect.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/Preview.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/ProblemTypeSelect.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/index.jsx
src/editors/data/constants/problem.js

JIRA Tickets: [TNL-10356](https://2u-internal.atlassian.net/browse/TNL-10356), [TNL-10359](https://2u-internal.atlassian.net/browse/TNL-10359), and [TNL-10357](https://2u-internal.atlassian.net/browse/TNL-10357)
This PR changes the following:
1.  the containers on the Problem Select page from flex to fixed sizes
2. "Blank advance problem" to "Blank advanced problem"
3. remove box shadow from problem select buttons

feat: make problem select and preview a fixed size

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap

JIRA Tickets: [TNL-10374](https://2u-internal.atlassian.net/browse/TNL-10374) and [TNL-10375](https://2u-internal.atlassian.net/browse/TNL-10375)
This PR fixes the Advanced Problem Editor confirmation dialog not closing on confirmation and scrolls to the top of the page after confirmed.

feat: update onclick to close modal + top scroll

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap
src/editors/sharedComponents/RawEditor/__snapshots__/index.test.jsx.snap
src/editors/sharedComponents/RawEditor/index.jsx
src/editors/sharedComponents/RawEditor/index.test.jsx

JIRA Tickets: [TNL-10358](https://2u-internal.atlassian.net/browse/TNL-10358), [TNL-10393](https://2u-internal.atlassian.net/browse/TNL-10393), and [TNL-10394](https://2u-internal.atlassian.net/browse/TNL-10394)
This PR addresses the following issues:
1. Removes the error header in the advanced problem editor
2. Removes the "Switch to advanced editor" button from the settings stack when user is in the advanced editor
3. Update the confirm button in the switch to advanced editor dialog to use sentence casing

feat: update styling in advanced problem editor

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/__snapshots__/FeedbackBox.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.test.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/problem/reducers.test.js

JIRA Ticket: [TNL-10377](https://2u-internal.atlassian.net/browse/TNL-10377)
Previously, when feedback was added to either the "selected feedback" field or the "unselected feedback" field, it would appear in both fields. This PR changes the fields `onChange` function to properly update the respective fields.

fix: separate feedback onchange for each field

---

src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/index.jsx

JIRA Ticket: [TNL-10408](https://2u-internal.atlassian.net/browse/TNL-10408)
This ticket fixes the margin error that caused the footer on the `SelectTypeModal` screen to overlap with the content on the page. After adding margins to the `ModalDialog.Body`, all content can be seen and the footer remains fixed at the bottom.

feat: add margin to prevent footer blocking content

---

package-lock.json
package.json
src/editors/containers/ProblemEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
src/editors/containers/ProblemEditor/hooks.js
src/editors/containers/ProblemEditor/hooks.test.js
src/editors/containers/ProblemEditor/index.test.jsx
www/package-lock.json
www/package.json

JIRA Ticket: [TNL-10396](https://2u-internal.atlassian.net/browse/TNL-10396)
This PR adds a custom "Label" button to the question widget's tinyMCE. Label tags are used by screen readers and emphasis the main question. Previously label tags were converted to strong tags, and with this change the tags are maintained. 
One thing to note is that tinyMCE requires all text to be wrapped in valid block tags. Therefore, label tags have to be wrapped inside paragraph tags. To keep the rendering of the olx inside the tinyMCE editor from rearranging the text, all labels have to be in their own paragraph. This means that whenever a label is added, a new paragraph is also added.
Simple Example:
Raw OLX
```
<p>This is an example</p><label>This is the important part</label>
```
translates to
```
<p>This …
```

feat: add label button to question tinyMCE

---

src/editors/containers/ProblemEditor/hooks.js
src/editors/containers/ProblemEditor/hooks.test.js

This PR fixes the `endsWith` bug when a question was not defined or an empty string. Previously, the label parser assumed the question would have a length. Now, if the question is undefined or an empty string , it will not be parsed for labels.

fix: add check for question length for parser

---

src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx

JIRA Ticket: [TNL-10407](https://2u-internal.atlassian.net/browse/TNL-10407)
This PR changes the z-index for the `SelectTypeModal` header. Previously, the header would be covered by the content in the main body when the page was scrolled. Now, the content scrolls below the header preventing, a visual conflict.

fix: selectTypeModal header z-index

---

src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js

This PR seeks to correct the following error which was triggering when attempting to save number only answers.
```
Uncaught TypeError: o.default.get(...).trim is not a function
at e.value (ReactStateOLXParser.js:252:53)
at ReactStateOLXParser.js:47:16
at Array.forEach (<anonymous>)
at e.value (ReactStateOLXParser.js:44:13)
at e.value (ReactStateOLXParser.js:107:31)
at e.value (ReactStateOLXParser.js:263:30)
at hooks.js:12:47
at hooks.js:27:14
at Object.s (react-dom.production.min.js:14:84)
at d (react-dom.production.min.js:14:238)
```

feat: react to OLX parser process number answers

---

src/editors/containers/EditorContainer/components/TitleHeader/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/TitleHeader/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeRow.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeCard.test.jsx.snap

This PR makes changes to problem type selection in the problem editor. When the problem type is changed through the problem type widget and the title of the block is a default value, the title will update to match the new problem type.
https://2u-internal.atlassian.net/browse/TNL-10399

feat: change title when problem type changes

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

JIRA Ticket: [TNL-10428](https://2u-internal.atlassian.net/browse/TNL-10428)
Previously, when a user created a problem and saved it without adding an answer, they would be redirected to the advanced editor page because the parser did not check for an empty answer array. Now if a problem does not have answers, the parser adds an empty answer to the problem and takes the user to the visual editor.

fix: add empty answer to problem without answers

---

src/editors/containers/ProblemEditor/components/EditProblemView/index.scss

Fix to merged change https://github.com/openedx/frontend-lib-content-components/pull/234.
Advanced selection was showing green radio buttons. This PR will only apply green radio and checkboxes to radio and checkboxes with the isValid attribute set to true.

feat: green radio+checkbox only for valid Checker

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

feat: multiple numericalresponse tags no longer special-cased against going to the advanced editor. TNL-10426.

feat: multiple numericalresponse tags no longer special-cased against going to the advanced editor. TNL-10426.

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/data/redux/problem/reducers.js

This PR allows multiple correct answers to be selected in problem editor's single select type. This is due to feedback that course authors may want multiple correct answers even though learners can only select one answer to respond with.
https://2u-internal.atlassian.net/browse/TNL-10430

Feat  allow singleselect to accept multiple correct answers

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/data/SettingsParser.js
src/editors/containers/ProblemEditor/data/SettingsParser.test.js
src/editors/containers/ProblemEditor/data/mockData/problemTestData.js
src/editors/data/redux/problem/reducers.js

fix: more correct parsing of settings, for scoring; use empty string instead of null for empty attempts. TNL-10433.

fix: more correct parsing of settings, for scoring; use empty string instead of null for empty attempts. TNL-10433.

---

src/editors/containers/ProblemEditor/data/OLXParser.js

This PR resolves the bug in the OLXParser inside the `getGeneralFeedback` function. The function expected that all answers would have `selectedFeedback` defined. However, when a single select or dropdown problem are opened without answers, `selectedFeedback` is not defined. This caused these problems to be rendered in the Advanced Editor when they should be rendered in the visual editor.

fix: getGeneralFeedback selectedFeedback error

---

src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/index.jsx
src/editors/containers/EditorContainer/components/EditorFooter/index.test.jsx

This PR adds a feedback link to the problem editor for beta data collection purposes. We plan to remove it when the beta concludes. The link presently needs problems added to it, but that is work for our product person.

feat: add feedback link

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/GroupFeedbackRow.test.jsx.snap

This PR makes this:
look like this:
It specifically address the Group Feedback widget's checkbox coloring.

feat: fix checkbox colors for feedback

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintsCard.jsx

This PR removes the Hints widget from the advanced editor. Hints shows up as a tag in the OLX so it should not be a widget.
https://2u-internal.atlassian.net/browse/TNL-10457

feat: remove Hints widget from advanced editor

---

src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

This PR moves the solution tag inside the problem type tag. When a problem block has multiple problems, each problem has their respective solutions. This change sets the user up for when they switch to the advanced editor.
https://2u-internal.atlassian.net/browse/TNL-10458

feat: move solution tag inside problem type tag

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/index.scss
src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
src/editors/sharedComponents/RawEditor/__snapshots__/index.test.jsx.snap
src/editors/sharedComponents/RawEditor/index.jsx
src/editors/sharedComponents/RawEditor/index.test.jsx

JIRA Ticket: [TNL-10402](https://2u-internal.atlassian.net/browse/TNL-10402)
This PR fixes the width of the settings column in the advanced problem editor view. The raw editor was overriding the `flex-grow-1` class and requires its own width styling.

fix: settings col width in advanced view

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ResetCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ResetCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ResetCard.test.jsx.snap

ACs: Clicking the hyperlink in the reset card brings you to the course's advanced settings.

feat: reset card link works

---

src/editors/data/constants/advancedOlxTemplates/circuitschematic.js
src/editors/data/constants/advancedOlxTemplates/customgrader.js
src/editors/data/constants/advancedOlxTemplates/jsinput_response.js
src/editors/data/constants/advancedOlxTemplates/problem_with_hint.js

Several advanced problem types do not work out of the box. This PR should ensure that the initial template for the following types can be saved and will work in studio:
- Circuit schematic builder
- Custom JavaScript display and grading
- Custom Python-evaluated input
- Problem with adaptive hint
https://2u-internal.atlassian.net/browse/TNL-10473
https://2u-internal.atlassian.net/browse/TNL-10474

feat: fix initial advanced problem type olx

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js

JIRA Ticket: [TNL-10445](https://2u-internal.atlassian.net/browse/TNL-10445)
This PR addresses a bug that prevented answers from clearing out for dropdown problems when multiple answers were selected a second time. Previously, the answers cleared out as expected when a user first changed from a multi-answer problem to a single answer problem. However, if the user reselected multiple answers and went back to a single answer problem, the answers were not deselected. Now, the user can go back and forth between the problem types with multiple answers selected and problem types with single answers with the answers clearing out when necessary.

fix: check for if an answer changes to false

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/LanguageSelector.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/LanguageSelector.test.jsx.snap

This PR switches out the form control select component for the dropdown component, as the result of this dropdown is to open a file upload dialog.
An upload dialog cannot be opened from a non-user action. 
A select's on change event is not a user action, so the component cannot be used.
Some minor styling changes may occur, but I tried to match the experiences as best I could, particularly re: a11y.

fix: file upload on safari

---

src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
src/editors/containers/ProblemEditor/hooks.js
src/editors/containers/ProblemEditor/hooks.test.js
src/editors/containers/TextEditor/hooks.js
src/editors/containers/TextEditor/hooks.test.jsx
src/editors/data/constants/tinyMCEConfig.js

This PR makes the following changes:
- moves tinyMCE config out of Text Editor folder to a shared space
- separates config into shared, textEditor and problemEditor config
- adds valid_elements and valid_children to the Problem Editor config to fix blank space issues
https://2u-internal.atlassian.net/browse/TNL-10477

feat: tinyMCE config changes

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/problem/reducers.test.js

Based on [Read the Docs](https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/numerical_input.html), numeric input problem type does not save incorrect answers. This should be reflected in the UI.
This PR makes the following changes:
- Checkboxes are disabled and checked for numeric input
- Switching to and from numeric input problem type works as expected
- Adding answers for numeric input works as expected
https://2u-internal.atlassian.net/browse/TNL-10500

feat: numeric input UI to allow only correct

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

Explanation data was not being parsed because the test data was malformed-- the explanation actually goes INSIDE the input tag. This PR solves this issue in the parser, as well as it's test data.
https://2u-internal.atlassian.net/browse/TNL-10501
and https://2u-internal.atlassian.net/browse/TNL-10504

fix: parse explanation data correctly.

---

src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/index.jsx
src/editors/containers/EditorContainer/hooks.js
src/editors/containers/EditorContainer/hooks.test.jsx
src/editors/containers/EditorContainer/index.jsx
src/editors/containers/EditorContainer/index.test.jsx
src/editors/hooks.js
src/editors/hooks.test.jsx

A toast error appears on editors when a save operation failed. Currently, the toast cannot be closed. This PR would allow the toast to be closed.
https://2u-internal.atlassian.net/browse/TNL-10455

feat: clear save failed status when closing error

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/__snapshots__/FeedbackBox.test.jsx.snap
src/editors/data/redux/problem/reducers.js

Based on how OLX works, only Multi-select problem types use not-select feedback. This can be seen in chapter 10 of Read the Docs: https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/exercises_tools/checkbox.html#configure-individual-option-feedback
This PR limits not-select feedback to only Multi-select problem types.

Feat  allow not select feedback for only multi select problem type

---

CODEOWNERS
catalog-info.yaml

This is related to Maintainership Pilot expectations. 
- CODEOWNERS file will notify teaching-and-learning team members of PR submissions, but there are currently no additional branch protections related to this ownership.
- catalog-info.yaml populates Backstage info for the Open edX community. It helps identify that tnl is the owner of this component. This is in relation to Maintainership OEP-55.

chore: add missing maintainership files

---

src/editors/sharedComponents/Button/index.scss

The add answer button was missing an outline, which is bad for accessibility.
https://2u-internal.atlassian.net/browse/TNL-10510

fix: answer button accessibility

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/constants.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/messages.js
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/data/redux/problem/reducers.js

This Adds a new "Tolerance" setting to numerical input problems.
Testing isntructions:
- Create a numeric problem
- Create at least one answer
- Add a tolerance with the setting.
- Save
- See tolerance work in studio (answer is forgiving)
- Open back up editor, 
- Tolerance is loaded in.

feat: tolerance Setting Widget

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx

When a course author is editing a video XBlock in the new video editor, for YouTube videos the option to import transcripts only appears after adding the URL, saving the XBlock and opening it for editing again. This PR makes the popup appear as soon as the YouTube URL is added and certain validations have passed, without having to save the and enter the editor again.
If you're going to test on devstack, here are the setup steps:
1. Setup `master` devstack
2. Enable new video editor following [these instructions](https://github.com/openedx/frontend-app-course-authoring/blob/ad47bfacd4a4033572fd98e81ec16b51379f8325/README.rst#feature-new-react-xblock-editors):
* You don't need to set `COURSE_AUTHORING_MICROFRONTEND_URL`, as it's already set on devstack
* You can set …

feat: offer to import youtube transcripts dynamically

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/hooks.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/hooks.test.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/index.scss
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/messages.js

This PR contains some improvements for the video duration section.
Collapsed:
Expanded:
Collapsed:
Expanded:
1. Try to add a stop time for some video.
2. You should see the label outlined and right-aligned.
3. Collapse the widget.
4. You should see "Custom" label instead of "Total".
[private-ref](https://tasks.opencraft.com/browse/FAL-3356)

feat: video duration section improvements [BD-12]

---

src/editors/containers/ProblemEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.scss
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ResetCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ResetCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ShowAnswerCard.test.jsx.snap
src/editors/containers/ProblemEditor/index.jsx
src/editors/containers/ProblemEditor/index.test.jsx
src/editors/data/constants/requests.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/problem/reducers.test.js
src/editors/data/redux/problem/selectors.js
src/editors/data/redux/problem/selectors.test.js
src/editors/data/redux/requests/reducer.js
src/editors/data/redux/thunkActions/problem.js
src/editors/data/redux/thunkActions/problem.test.js
src/editors/data/redux/thunkActions/requests.js
src/editors/data/services/cms/api.js
src/editors/data/services/cms/types.js

JIRA Ticket: [TNL-10429](https://2u-internal.atlassian.net/browse/TNL-10429)
This PR adds "(Default)" to the attempt field and show answer field when the user selects/enters the default value defined in the courses advanced settings. Additionally this PR sets the attempt field, show answer field, and show reset button value to the course's default value when creating a new problem.

feat: add default advanced setting ui callouts

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

This change increases the frequency at which odd tags (like shuffle) on multiple choice problems don't go to the visual editor.
Instead, they will now divert to the advanced editor. There might be other places where we need to follow a similar pattern, but we don't know those yet.
Testing instructions:
- Follow the process of creating a shuffle problem in advanced editor using this olx: (edit this Q to get the xml)
```
<problem>
<multiplechoiceresponse>
<label>What Apple device competed with the portable CD player?</label>
<choicegroup type="MultipleChoice" shuffle="true">
<choice correct="false">The iPad</choice>
<choice correct="false">Napster</choice>
<choice correct="true">The iPod</choice>
<choice correct="false">The vegetable peeler</choice>
</choicegroup>
</multiplechoiceresponse> …
```

feat: error on funky multiple choice tags.

---

src/editors/data/redux/problem/reducers.js

Since every course has graded problems, every course author will be editing or creating problems, and every learner will need to receive points for any problem in a graded assignment in order to earn a passing grade. So if what I encountered and am reporting here is reproducible, this should probably be addressed before the problem editor feature is released.

feat: default scoring to 1, not zero.

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/GroupFeedbackRow.test.jsx.snap
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/mockData/editorTestData.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
src/editors/data/services/cms/api.js
src/editors/data/services/cms/mockApi.js

This PR reverts the expanded text area changes applied for the Group Feedback widget. This is a proposed change to the Group Feedback not saving properly for the simple problem editor.
https://2u-internal.atlassian.net/browse/TNL-10604

feat: revert group feedback expanded text field

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

When the simple problem editor loads OLX, the XMLBuilder encodes the OLX before tinyMCE decodes it again. This means that if the block contains any encoded HTML entities, they will not appear decoded on the editor.
LMS simply decodes the OLX. The simple editor should match that behavior.
An example of what is happening currently:
LMS: ` `
Block OLX: `&#160;`
After XMLBuilder processing: `&amp;#160;`
After tinyMCE processing: `&#160;`  (this is what is seen in the simple problem editor)
This PR keeps XMLBuilder from encoding the OLX.
https://2u-internal.atlassian.net/browse/TNL-10627
=========================
Somewhat related, the XMLParser automatically parses numbers like 0x12 as hexes. This PR will turn this parsing off as well.
https://2u-internal.atlassian.net/browse/TNL-10629

feat: XMLBuilder and XMLParser performing unwanted processing in encoding / parsing 

---

src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/editorTestData.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

This PR ensures we do not parse numbers the following ways on save:
- hex -> dec
- remove leading 0's

feat: further number parse changes

---

package-lock.json
package.json
src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/messages.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/hooks.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/messages.js
src/editors/sharedComponents/CodeEditor/hooks.js
src/editors/sharedComponents/CodeEditor/index.test.jsx

JIRA Ticket: [TNL-10609](https://2u-internal.atlassian.net/browse/TNL-10609)
When a course author is using the advanced problem editor and they have malformed xlm, there is a toast message that appears notifying them that their changes could not be saved and to try again later. This message does not clearly communicate to the author the actual error in the xlm. The PR adds a xlm linter plugin to code mirror. When the xlm is malformed, such as unclosed tags, a red squiggle will appear at the location of the error. On hover a message describing the error will appear.

feat: add xml linter to code mirror

---

src/editors/sharedComponents/CodeEditor/hooks.js
src/editors/sharedComponents/CodeEditor/index.test.jsx

Currently is `textArr` is undefined, the `syntaxChecker` returns an error because `.join` can only run on arrays. This PR has the checker return an empty array if `textArr` is undefined.

fix: textArr join error in syntaxChecker

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/CardSection.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/CardSection.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/GroupFeedbackRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/GroupFeedbackRow.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/GroupFeedback/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap

JIRA Ticket: [TNL-10451](https://2u-internal.atlassian.net/browse/TNL-10451)
This PR changes the font sizes in the opened view of the setting widgets from small to extra small and adjusts the spacing between text. Additionally, this PR fixes the text for the Randomization widget to match the expect experience when there is no randomization (null).

fix: settings font size and spacing

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintRow.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/HintRow.test.jsx.snap

In problem editor settings:
|
|
v

feat: hint trash button should not be squished

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/CardSection.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/CardSection.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.scss

JIRA Ticket: [TNL-10451](https://2u-internal.atlassian.net/browse/TNL-10451)
This PR is an extension of [PR 308](https://github.com/openedx/frontend-lib-content-components/pull/308). The helper text font size and padding on the setting widgets did not populate in stage. Something causes the behaviors for `Collapsible` components font inheritance and padding to differ between the openedx and edx themes.

fix: settings helper text font size

---

src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/mockData/editorTestData.js
src/editors/sharedComponents/TinyMceWidget/pluginConfig.js

Blocks that look like this:
are turning into this when just opening and saving the block without changes:
The weird spacing and formatting is due to how studio displays text wrapped in a `<p>` block tag. Before the visual problem editor update, this text was not wrapped in `<p>`. However, tinyMCE requires text to be wrapped in block tags.
This PR fixes this by doing the following:
1. Have tinyMCE default to a `<div>` block tag instead of a `<p>` block tag. Allow selection of div block tag.
2. Strip the block tag around `<label>` tags.
Internal ticket: https://2u-internal.atlassian.net/browse/TNL-10632

feat: tinyMCE formatting and parsing

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Randomization/messages.js
src/editors/data/constants/problem.js

In the problem editor, the randomization setting is typically used for randomization with a python script. However, the setting is also needed for the shuffle answer functionality. This PR ensures that the randomization setting can be configured for all problems and defaults the setting to 'never'.
Jira: https://2u-internal.atlassian.net/browse/TNL-10652

feat: default randomization to never

---

src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/TitleHeader/EditableHeader.jsx
src/editors/containers/EditorContainer/components/TitleHeader/__snapshots__/EditableHeader.test.jsx.snap
src/editors/containers/EditorContainer/components/TitleHeader/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/TitleHeader/index.jsx
src/editors/containers/EditorContainer/index.jsx

JIRA Ticket: [TNL-10427](https://2u-internal.atlassian.net/browse/TNL-10427)
This PR fixes the width of the editable header. Previously the editable header only took up a third of the row making it difficult to read. Now the editable header takes up almost all the row, leaving a resonable gap to prevent confusion with the close editor icon.

fix: editable header width

---

src/editors/data/services/cms/urls.js

This PR keeps the page from erroring and looping when no ancestor pages come back in the response.

feat: page errors indefinitely with no ancestor

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/messages.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/index.jsx
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js
src/editors/data/redux/video/reducer.js
src/editors/data/redux/video/selectors.js
src/editors/data/services/cms/api.js
src/editors/data/services/cms/api.test.js

JIRA Ticket: [AU-1188](https://2u-internal.atlassian.net/browse/AU-1188)
This PR moves the checkbox that allows public access to video into its own widget/section. The section is not rendered if the waffle flag `video_config.public_video_share` is disabled. The checkbox is disabled when the setting is set at the course level and enabled when the setting is set on video-by-video basis.
This PR is dependent on [edx-platform PR 32157](https://github.com/openedx/edx-platform/pull/32157).

feat: add social share widget

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.test.jsx
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js
src/editors/data/redux/video/reducer.js
src/editors/data/redux/video/selectors.js

Follow-up to [PR 323](https://github.com/openedx/frontend-lib-content-components/pull/323). This PR is dependent on [edx-plaform PR](). This change makes the social share widget available in libraries. The social share widget is on a per-video basis.

feat: allow social share widget in libraries

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.test.jsx

When a course has 'all-on' or 'all-off' for the social sharing in the course outline, there should be two messages under the checkbox notifying the user that the setting overridden by the course settings and that they can be changed on the course outline page. When a course has 'per-video' for the social sharing in the course outline, there will be no messages bewlow the checkbox.

fix: show setting note for course set social share

---

src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/messages.js
src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.test.js
src/editors/data/redux/thunkActions/problem.js

JIRA Ticket: [TNL-10619](https://2u-internal.atlassian.net/browse/TNL-10619)
A problem's metadata can be defined in the `<problem>` tags like the following:
```
<problem showanswer="always">raw olx</problem>
```
The presence of this attribute navigates to the advanced editor. However, the value of the attribute is not saved to the problem's metadata. This means that the intended value is not displayed in Studio or the LMS. This PR adds a function that parses the raw olx and updates the metadata according to the values in the olx. When the raw olx settings do not match the metadata settings, the user is notified of the difference. On confirmation the raw olx settings overwrite the corresponding metadata.

feat: add raw olx settings parser

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/data/constants/problem.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/problem/reducers.test.js
src/editors/sharedComponents/TinyMceWidget/hooks.js

[A previous PR](https://github.com/openedx/frontend-lib-content-components/pull/325) introduces an issue with expandable textarea where images can not be inserted anywhere except at the beginning of the textarea.
This PR fixes this by approaching the solution from a different way. The answer fields are saved to the state before deletion, allowing for the correct answer to be deleted.
This PR also allows the last answer to be deleted by wiping the values of the answer, selectedFeedback and unselectedFeedback text fields for this last answer when delete is clicked.
https://2u-internal.atlassian.net/browse/TNL-10644

fix: delete answers without changing expandable

---

src/editors/containers/VideoUploadEditor/hooks.js

This PR is a little fix of https://github.com/openedx/frontend-lib-content-components/pull/326
I deleted a line that was used to test the video upload functionality.

fix: Temporal testing line deleted from VideoUploadEditor::hooks.js

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js

When a user changed from a single select or multi-select problem type to another, the feedback was cleared out. This is because the data wasn't stored in the redux store before the problem type was updated. Now when changing between problem types, the feedback is saved to the redux store.

fix: feedback clearing on type change

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js

JIRA Ticket: [TNL-10689](https://2u-internal.atlassian.net/browse/TNL-10689)
Currently if a user formats their text (italicize, bold, etc.) or adds an image all inside the same parent tag, e.g. `<p>`, the order of the text/image will be changed on save and re-open. This causes user to be confused and not trust the visual editor as it is not saving their work as expected. This PR uses `fast-xml-parser`'s attribute `preserve-order` to keep the text in the same order while parsing and building. This attribute is currently used for the question parser, and is now being applied to all places where tinymce is used.

fix: olx parsers with formatted text

---

src/editors/Editor.jsx
src/editors/EditorPage.jsx
src/editors/__snapshots__/Editor.test.jsx.snap
src/editors/__snapshots__/EditorPage.test.jsx.snap
src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/hooks.js
src/editors/containers/EditorContainer/index.jsx
src/editors/containers/EditorContainer/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx
src/editors/containers/ProblemEditor/index.jsx
src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/TextEditor/index.jsx
src/editors/containers/VideoEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/index.jsx
src/editors/hooks.js
src/editors/hooks.test.jsx

This PR adds a new prop, `returnFunction` to editors. This new prop is necessary for pages that use an editor, but are not connected to a Studio Unit page. This prop is used when exiting an editor (save or cancel).

feat: add returnUrl prop to editors

---

src/editors/data/redux/thunkActions/app.js
src/editors/data/redux/thunkActions/app.test.js
src/editors/hooks.js
src/editors/hooks.test.jsx

Related JIRA Ticket: [TNL-10796](https://2u-internal.atlassian.net/browse/TNL-10796)
This PR returns the xblock API response back to the parent component when `returnFunction` is defined. This is necessary when the editor data is changed and the change needs to be reflected on save.

feat: update returnToUnit to include api response

---

src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/index.jsx
src/editors/data/redux/thunkActions/app.js
src/editors/data/redux/thunkActions/app.test.js
src/editors/hooks.js
src/editors/hooks.test.jsx

This PR resolves the bug that caused the save failure toast to appear without an API save error. The toast was appearing because of a type error and the toast appeared whenever an error is caught during the save, but still allowed the save to continue. Additionally, resolves the bug that causes the close confirmation modal to remain open after closing the modal. The close confirmation modal was previously not closing so it would remain visible when the editor was not is a modal or redirected after closing.

fix: failure toast and close modal bugs

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/constants.js
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/hooks.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/hooks.test.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/SocialShareWidget/index.jsx
src/editors/data/redux/thunkActions/requests.js
src/editors/data/redux/thunkActions/requests.test.js
src/editors/data/services/cms/api.js
src/editors/data/services/cms/api.test.js
src/editors/data/services/cms/mockApi.js
src/editors/data/services/cms/urls.js
src/editors/data/services/cms/urls.test.js

When a user toggles the "social sharing" checkbox, sent an analytics event
This also includes a fix to an issue where we were requesting an old URL for the video features URL

feat: send event on checkbox change

---

src/editors/data/redux/app/reducer.js

This PR sets the `blockValue` to `null` when the editor is initializing. Reference [this comment](https://github.com/openedx/frontend-app-course-authoring/pull/510#pullrequestreview-1489201114) from course authoring PR 510 for testing details.

fix: persisting title from previous editor load

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswersContainer.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.test.jsx
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
src/editors/sharedComponents/ErrorBoundary/index.test.jsx
src/editors/sharedComponents/SelectionModal/index.test.jsx

This PR makes the following changes to the problem editor parser:
- `<div class="detailed-solution">` should not be required under the `<solution>` tag. The parser no longer requires this.
- The question field was only taking label, description, h1, h2, h3, h4, h5, h6, div, p and pre tags. This means tags like `<table>` and `<img>` are not parsed and get removed when re-editing. These changes fixes this.
- These changes also fix the issue of new lines of `<p>Explanation</p>` popping up after saving and re-editing.
This PR was made due to several issues that came in where parts of the problem was missing or `<p>Explanation</p>` was added.
https://2u-internal.atlassian.net/browse/TNL-10832
https://2u-internal.atlassian.net/browse/TNL-10840
https://2u-internal.atlassian.net/browse/TNL-10833

feat: parser changes

---

src/editors/containers/VideoGallery/hooks.js

The backend for hiding selected videos is not implemented and it is currently not required, so this commit hides the option.
**Test instructions**
Follow instructions provided in https://github.com/openedx/frontend-lib-content-components/pull/278 to get to video gallery page and make sure that the option `Hide selected videos` is not visible.
Before:
After:

refactor: hide switch to hide selected videos

---

src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoUploadEditor/hooks.js
src/editors/containers/VideoUploadEditor/hooks.test.js
src/editors/containers/VideoUploadEditor/index.jsx
src/editors/containers/VideoUploadEditor/index.test.jsx
src/editors/containers/VideoUploadEditor/messages.js
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

This PR refactors the functionalities and adds a loading spinner before making the upload video call. This is done so that we can avoid race conditions and re-try pages.
**Discussions**: None
**Dependencies**: None
**Screenshots**: Always include screenshots if there is any change to the UI.
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
~~**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.~~
**Testing instructions**:
1. Set up the master devstack, make sure you have course-authoring-mfe(frontend-app-course-authoring) running
2. We have to clone this repo in {EDX_DEVSTACK}/src directory.
3. Change the branch being used to `open-craft:farhaan/bb-7522-fix-spinner-for-video` and run `make build`
4. Follow the steps …

feat: Add loading spinner to the video upload page

---

package-lock.json
package.json
src/footer/Footer.jsx
src/footer/Footer.test.jsx
src/footer/index.jsx
src/footer/messages.js
src/index.jsx
src/setupTest.js

This a rebuild of the current studio footer using React. The footer should have the same content as the existing footer.
For testing use course-authoring [PR 532](https://github.com/openedx/frontend-app-course-authoring/pull/532). The footer can be seen on at the bottom of Pages & Resources.

feat: react based studio footer

---

src/footer/Footer.jsx

Typo in the edX partner portal button link lead to a broken url.

fix: partner portal typo

---

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/ExplanationWidget/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/QuestionWidget/index.test.jsx
src/editors/containers/TextEditor/index.test.jsx
src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
src/editors/sharedComponents/TinyMceWidget/index.jsx
src/editors/sharedComponents/TinyMceWidget/index.test.jsx
src/index.jsx

- added TinyMceWidget on export
- `frontend-app-course-authoring` [PR](https://github.com/openedx/frontend-app-course-authoring/pull/547)

feat: Add TinyMceWidget on export

---

src/editors/data/services/cms/urls.js
src/editors/data/services/cms/urls.test.js

1. open up a library block
2. should render as expected
3. test cancel and save capabilities

fix: blockId checks for v1 or v2 libraries

---

src/editors/data/redux/thunkActions/app.js
src/editors/data/redux/thunkActions/app.test.js

In frontend-lib-content-components, behavior for failed api requests is not setup correctly. Currently, when failing, the error message received is saved as the requested data value.
https://2u-internal.atlassian.net/browse/TNL-10972

feat: call failRequest on fetch failure

---

src/editors/data/redux/thunkActions/video.js

Fix for [new relic error](https://one.newrelic.com/alerts-ai/issue?account=88178&duration=259200000&state=a8934090-9fec-dbdf-14e5-7b0f28b91a5a) type error
Test
1. Open a video block
2. replace the video
3. block should load as expected with video id
4. Navigate back to unit page
5. create new video bloack
6. select video
7. block should load as expected with video id

fix: selectedVideo undefined error

---

src/editors/sharedComponents/TinyMceWidget/__snapshots__/index.test.jsx.snap
src/editors/sharedComponents/TinyMceWidget/index.jsx

https://2u-internal.atlassian.net/browse/TNL-10980
This fixes a bug where if you write characters in a problem editor answer, their order becomes reversed.
The problem was the introduction of a new prop `updateContent` in https://github.com/openedx/frontend-lib-content-components/pull/365, which had a naming conflict with an existing prop that was implicitly passed.
I renamed the newly introduced prop to `onChange`.
As far as I understand, the mentioned PR was in preparation to use the tinyMCEEditor in frontend-app-course-authoring. So the prop needs to renamed there as well when updating FLCC.
- Create a singleselect problem
- Add a new answer
- Type in a word like "abc"
- Text should appear in the right order - "abc", not "cba"

fix: answer text flipped

---

src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js

The XML formatting causes additional newlines and spaces to be added to preformatted content wrapped in `<pre>` tags. This disables the XML formatting to prevent that from happening.
1. Create a new problem with the following text in a *Preformatted* block:
```
In the following RISC-V assembly snippet, how many times would the beq instruction execute?
addi  s0, zero, 10
L1:  beq   s0, zero, L2
addi  s0, s0, -2
j     L1
L2:
```
2. Ensure that the problem is displayed correctly with no additional spaces or newlines:

[TNL-10888] fix: preformatted content being re-formatted

---

src/editors/sharedComponents/TypeaheadDropdown/index.jsx
src/editors/sharedComponents/TypeaheadDropdown/index.test.jsx

JIRA Ticket: [TNL-11018](https://2u-internal.atlassian.net/browse/TNL-11018)
This PR sorts the items for the typeahead dropdown before the items are rendered into buttons.

fix: sort items in typeahead dropdown

---

src/editors/data/redux/app/selectors.js
src/editors/data/redux/app/selectors.test.js

JIRA Ticket: [TNL-11019](https://2u-internal.atlassian.net/browse/TNL-11019)
This PR adds a check to the `isLibrary` selector to catch v2 libraries. The `isLibrary` selector controls if images are in tinymce toolbars.
Testing
1. Open a v2 library and check that the image button is not in the toolbar.
2. Open a v1 library and check that the image button is not in the toolbar.
3. Open a course block and check that the image button is in the toolbar.

feat: update isLibrary check to include v2 libs

---

src/editors/containers/VideoEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoEditorModal.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/index.jsx
src/editors/containers/VideoEditor/index.jsx
src/editors/containers/VideoEditor/index.test.jsx

JIRA Ticket: [TNL-11022](https://2u-internal.atlassian.net/browse/TNL-11022)
This PR removes the "Replace video" when the video block is used in a v1 and v2 library.
Note: This PR depends on PR #389 
Testing
1. Open a v2 library and check that the replace button is not iat the top.
2. Open a v1 library and check that the replace button is not at the top.
3. Open a course block and check that the replace button is at the top.

feat: remove replace video button for libs

---

src/editors/containers/VideoUploadEditor/VideoUploader.jsx
src/editors/containers/VideoUploadEditor/__snapshots__/VideoUploader.test.jsx.snap
src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoUploadEditor/index.jsx
src/editors/containers/VideoUploadEditor/index.scss

The PR fixes styling issues with the Dropzone component.
Error Page
1. The Dropzone component doesn't have the ability to change the cursor on dragging the file which raises a validation error.
1. Set up the master devstack, make sure you have course-authoring-mfe(frontend-app-course-authoring) running
2. We have to clone this repo in {EDX_DEVSTACK}/src directory.
3. Change the branch being used to current branch and run `make build`
4. Follow the steps mentioned in https://github.com/openedx/frontend-lib-content-components/pull/262 to set up video editor, make sure to `Step 3 - Step 7`
5. We need to upload a small video and connect it to the demo course as mentioned in https://github.com/openedx/frontend-lib-content-components/pull/326
6. We need to make changes to the edx-platform to …

fix: Fix styling for components in dropzone

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ResetCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/data/constants/problem.js

JIRA Ticket: [TNL-11023](https://2u-internal.atlassian.net/browse/TNL-11023)
Currently all problems in v2 libraries open in the advanced editor. This is because the problem settings are being added to the wrapping `<problem>` tag and threw a "Misc. Attributes" error. This data is duplicated in the problem metadata. This PR adds a check to the OLX parser to only throw "Misc. Attributes" error if the attributes are not settings.
Testing
**Repeat test in a v2 library, v1 library, and course**
1. Create a new common problem, fill out fields, and save.
2. Edit the block and it should open in the simple editor.
4. Choose to open in the advanced editor.
5. Add an attribute to the `<problem>` tag (e.g guess="no") and save.
6. Edit the block and it should open in the advanced editor.
7. Create a …

fix: v2 libraries default open to advanced editor

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/index.jsx
src/editors/data/redux/app/selectors.js
src/editors/data/redux/app/selectors.test.js
src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

JIRA Ticket: [TNL-11024](https://2u-internal.atlassian.net/browse/TNL-11024)
Currently, video license info does not appear in v2 content libraries after saving a block with the data. This is because the `studio_view` in v2 libraries has a different attribute name for the html. v2 libraries use "content" instead of "html". This PR adds an additional check for `studio_view.data.content` whenever `studio_view.data.html` is checked.
Testing
1. Open a v2 library.
2. Create a video block and edit the license widget
3. Save block.
4. Reopen block and check that the license widget loads as expected
5. Open a unit.
6. Create a video block and edit the license widget
7. Save block.
8. Reopen block and check that the license widget loads as expected
9. Should render without errors.
10. Create a raw …

fix: empty v2 library studio view

---

src/editors/containers/VideoUploadEditor/VideoUploader.jsx
src/editors/containers/VideoUploadEditor/__snapshots__/VideoUploader.test.jsx.snap
src/editors/containers/VideoUploadEditor/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoUploadEditor/index.scss
src/editors/sharedComponents/TypeaheadDropdown/index.jsx

The styles added to the video upload page was forcing all the form controls to be a fixed size and their trailing elements to render outside of the form control. Now the added styling only applies to the video upload page, as was originally intended. This PR also changes the sort method for the typeahead dropdown. The previous sort method was an in-place sorter so half of the time it would throw an error and not render the list of options.
Testing
1. Navigate to the studio home page.
2. Click "New course".
3. All input boxes should span the width of the main body.
4. Click the expand option for in the organization input.
5. Should render list of options with no errors.
6. Begin typing in the input
7. Should update rendered list with no errors

fix: typeahead sort and styling

---

package.json
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.test.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
src/editors/containers/ProblemEditor/data/SettingsParser.js
src/editors/containers/ProblemEditor/data/SettingsParser.test.js
src/editors/containers/ProblemEditor/data/mockData/problemTestData.js
src/editors/data/redux/problem/reducers.js
src/editors/data/redux/thunkActions/problem.js

The max attempts setting for a problem xblock should be set to null for course default max attempt setting to take effect. This makes sure that xblock setting is updated if course default is updated.
`Private-ref`: [BB-7940](https://tasks.opencraft.com/browse/BB-7940)
**Test instructions:**
* To reproduce the issue
* Setup master devstack and follow steps provided in the README to use the new problem editor.
* Enable `new_core_editors.use_new_text_editor` and `new_core_editors.use_new_problem_editor` waffle flag.
* Update Maximum attempts setting in advanced setting for the course.
* Select any problem in demo course or create a new problem.
* Set Maximum attempts as default by clearing the field or entering the same number as default.
* Go to advanced settings
* Change the default …

fix: make max attempts setting fallback to default 

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/messages.js

According to the documentation (https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/video/additional_video_options.html#thumbnail)
video thumbnail is only available for videos uploaded through the "Video Uploads" page (https://edx.readthedocs.io/projects/edx-partner-course-staff/en/latest/video/upload_video.html).
Additional conditions for the availability of the "Upload thumbnail" button have been added in the case when we upload video transcripts, a unique "Video ID" is created, but the thumbnail should still not be available for downloading since we use third-party video sources.
The text of the message for the thumbnail block was also changed, indicating the specific availability of functionality.

fix: video thumbnail availability

---

src/editors/data/services/cms/api.js
src/editors/data/services/cms/api.test.js

Internal issue: https://2u-internal.atlassian.net/browse/TNL-11299
When you go to library-authoring locally and click the edit button on a text or problem block, the tinyMceEditor does not load, but goes to an infinite loading spinner. This is fixed here.
- pull latest library-authoring master
- run `make build` in this frontend-lib-content-components repo
- restart library-authoring container
- go to `localhost:3001`, open a library, and try to edit a text block.
- You may get an error `Syntax Error: unexpected token <`. This is an unrelated error. To ignore this, go to file `src/editors/data/constants/tinyMCE.js`, to line 57 with `export const plugins = listKeyStore([`, and then down to the lines 70-71 with `  'a11ychecker',
'powerpaste',` and comment out both lines. Then run `make …

fix: get library blocks editing to work locally

---

src/editors/Editor.jsx
src/editors/__snapshots__/Editor.test.jsx.snap
src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/index.jsx
src/editors/containers/EditorContainer/index.scss

Testing instructions:
- open editors and paste a huge amount of text into it so you need to scroll down
- Text editor scrolls normally, doesn't have double scroll bar, and behaves / looks normal
- Video editor scrolls normally, doesn't have double scroll bar, and behaves / looks normal
- Problem editor scrolls normally, doesn't have double scroll bar, and behaves / looks normal
Note that you may encounter a problem I have been having locally, where you cannot open the tinyMceEditor but get `SyntaxError: unknown <`. This is to my knowledge only a local problem. To temporarily ignore it, go to src/editors/data/constants/tinyMCE.js and comment out this. Please only locally for yourself, don't commit:
`  'a11ychecker',
'powerpaste',`

fix: editor container can scroll again

---

src/editors/data/constants/tinyMCE.js

Previous commit didn't create a release. So I prefixed the commit with "fix: ".

Fix  disable tinymce powerpaste and a11ychecker plugins

---

src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/containers/ProblemEditor/data/OLXParser.test.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js
src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js
src/editors/containers/ProblemEditor/data/mockData/olxTestData.js

internal issue: https://2u-internal.atlassian.net/browse/TNL-11311
This fixes a bug where the editor was deleting the <description> OLX tag when editing in the simple editor and then saving.
Also the description was being converted to em for the simple editor, but then not converted back. However, the xblock renders label and then em in reverse order for some reason.
To fix it, the em gets converted back to description now, but not for every em tag (added a class "olx_description" for the tags that should be converted).
Testing:
- Copy the OLX below to a new advanced blank problem and save.
- The description should be visible in the course outline.
- Open problem again in simple editor. The content of the description tag should be visible as italics.
- save and check course outline. The …

fix  editor deleting description

---

src/editors/data/services/cms/api.js
src/editors/data/services/cms/api.test.js

Internal issue: https://2u-internal.atlassian.net/browse/TNL-11299
In library-authoring, content blocks could not be edited locally due to some problem with the Accept header. This caused some 404s. Visually you would get an infinite loading spinner.
This depends on https://github.com/openedx/frontend-app-library-authoring/pull/399.
- add `MFE_NAME='frontend-app-library-authoring'` to .env.development in your local frontend-app-library-authoring. (I'll add an extra PR for that now as well).
- test that your local course-authoring opens text blocks and that you can edit and save them. (In a previous attempt to fix this, the change broke course-authoring.)
- test that your local library-authoring opens text blocks and that you can edit and save them.
- When code reviewing, pay attention …

fix: library editor not working locally

---

src/editors/data/redux/thunkActions/video.js
src/editors/data/redux/thunkActions/video.test.js

JIRA Ticket: [TNL-11350](https://2u-internal.atlassian.net/browse/TNL-11350)
> Users can successfully upload videos, but they never leave the processing stage. Looking at the network tab it looks like the upload to AWS fails, but the user is never notified of the failure.
This PR fixes the `PUT` to AWS to more closely align with the legacy API that uses AJAX and JQuery. This PR allow properly handles the failure state of the `PUT` request when the API return a failure message.
Note: This PR requires a successfully set up video pipeline to properly test
Testing
1. Open a course unit
2. Add a new video block
3. Open network tab
4. Upload a video
5. User should be redirected to the video editor
6. Save block
7. Open the Videos page
8. Check that the recently added video is listed
9. Status …

fix: video upload api fetch body

---

src/editors/sharedComponents/SelectionModal/Gallery.jsx
src/editors/sharedComponents/SelectionModal/GalleryCard.jsx
src/editors/sharedComponents/SelectionModal/__snapshots__/GalleryCard.test.jsx.snap

This fixes a bug where images and videos are not clickable when using the Gallery component.
Please see https://github.com/openedx/frontend-lib-content-components/pull/460 for a full description of the bug.

Fix: selectable box in gallery

---

src/editors/containers/VideoEditor/components/VideoEditorModal.jsx

JIRA Ticket: [TNL-11505](https://2u-internal.atlassian.net/browse/TNL-11505)
> It was reported an issue regarding videos not populating the Video ID field when uploading a video via the video component. This issue results in the display of an error message stating, “No playable video source found,” due to the absence of the video ID in the designated field. A workaround for this video issue is to manually copy the video ID from the video block and paste it into the Video ID field.
Testing
1. Open a course.
2. Edit to the video component.
3. Click "Replace video"
4. Select the desired video for the unit.
5. The video will upload with the Video ID

fix: remove useEffect that fires before search params

---

src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
src/editors/containers/ProblemEditor/data/ReactStateSettingsParser.js
src/editors/containers/ProblemEditor/data/SettingsParser.js

JIRA Ticket: [TNL-10995](https://2u-internal.atlassian.net/browse/TNL-10995)
Description
Currently when a problem is saved with the default setting (focusing on max attempts, show answer, show reset button, and randomization). The current behavior assigns the default values to the block on save; however, this causes issues when a course author changes the default setting values. The author has to go back to all the blocks and manually update the blocks to the new default settings. This PR fixes this bug and does not save the default values to the block. The setting are only saved to the block if they differ from the default values. 
Testing
1. Create a Problem
2. Add content and leave settings untouched.
4. Go to the Advanced Settings page
5. Change the default maximum attempt settings
6. …

fix: default setting not updating with updated default settings

---

src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js
src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.test.jsx
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
src/editors/containers/ProblemEditor/data/SettingsParser.js
src/editors/data/redux/problem/reducers.js
src/editors/utils/index.js
src/editors/utils/snakeCaseKeys.js
src/editors/utils/snakeCaseKeys.test.js

This PR fixes problems where the maximum attempts is null by default. Previously, when a course had unlimited attempts by default and a user created a new problem, the unlimited option was not checked so the scoring card said, "1 point • 0 attempts". Now for new problems the unlimited option is checked and the card reads, "1 point • Unlimited attempts". This PR allows resolved the issue when changing a problems number of attempts from unlimited to a number and back to unlimited, the revert back to unlimited was not saved. This is because the default value of settings is not saved to problems so that it is able to automatically update if the default settings are changed. However, not saving the unlimited value did not revert the problem back to use the default maximum attempts. Now the …

fix: parser not saving unlimited attempts

---

.github/workflows/ci.yml
.github/workflows/release.yml

Update codecov to the latest version and start using the org-wide token for uploads.
See https://github.com/openedx/wg-frontend/issues/179

build: Update codecov and use token

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js

For legacy, the `Number of attempts` parameter does not affect `After all attempts` and `After all attempts` or correct.
Therefore, this field should not appear when these options are selected.
Even the name of these options contradicts the appearance of this field.
Now the "**NUMBER OF ATTEMPTS**" field is available only for the "**AFTER SOME NUMBER OF ATTEMPTS**" option

fix: Not used Number of attempts field for "After all attempts" and "After all attempts or correct"

---

src/editors/sharedComponents/ImageUploadModal/index.jsx
src/editors/sharedComponents/ImageUploadModal/index.test.jsx
src/editors/sharedComponents/TinyMceWidget/hooks.js
src/editors/sharedComponents/TinyMceWidget/hooks.test.js

This PR fixes a bug introduced in #480 where content that is inserted like pasting and adding images always inserted it at the beginning of the block, not where the cursor was last placed. This bug appeared because the content was updated before the insert happened so the cursor was moved to the beginning of the block for the new content. This PR fixes the update function to only update the content when the content is actually changed, not on every editor click.
JIRA Ticket: [TNL-11663](https://2u-internal.atlassian.net/browse/TNL-11663) 🔒 
1. Open a tab for each page that uses the visual editors
- text editor
- problem editor
- course updates
2. Copy and paste text into various parts of the editor
- in the middle of a sentence
- end of block
- highlight and replace
3. Add an image
- in …

fix: image and paste insert

---

src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap
src/editors/containers/EditorContainer/components/EditorFooter/index.jsx
src/editors/containers/EditorContainer/components/EditorFooter/index.test.jsx

This PR removes a deprecated feedback form that was used specifically for 2U beta testing.
Github Issue #476 
1. Open an existing problem block
2. Confirm that the "Share feedback" link is no longer present

fix: remove deprecated feedback link

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.jsx

Corrected the typo in the prop name of the Alert component from 'varaint' to 'variant'. This change ensures the proper functioning of the alert in informational variant.

fix: correct typo in Alert component prop

---

src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js
src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
src/editors/containers/ProblemEditor/data/OLXParser.js
src/editors/data/redux/thunkActions/problem.js

This PR sets up future work for a new OLX parser. Since releasing the react based problem editor, there have been various bugs that come from the OLX parser not catching all the nuanced tags. Currently the default experience for the editor is the visual (TinyMCE) editor. The problem is navigated to the advanced editor if it uses an advanced problem tags, has multiple questions in a problem, and a non-default tag or attribute is found. This approach requires updates to the problem editor parser each time a new tag or attribute is brought to the developers attention so that the content that it is referencing is not lost by accidentally rendering the wrong editor. To simply the need for constant updates for new tags or attributes, the new OLX parser will have a specific list of tags and …

feat: add conditional for new parser beta testing

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/index.scss
src/editors/containers/VideoUploadEditor/index.scss

This fixes a bug where 900 kB of redundant CSS was being accidentally built and included in any MFE that uses this.
I was working on the Course Authoring MFE and trying to remove _all_ SCSS from the bundle as part of some [experiments](https://github.com/openedx/frontend-build/pull/566) I was doing. But somehow there was still 900kB+ of CSS in the final bundle! After much head-scratching I finally traced it down to two lines of code buried deep in in this dependency, `frontend-lib-content-components`. Any time you write `@import "@openedx/paragon/scss/core/core";`, it adds a _full_ copy of the entire Paragon CSS to the build (around 400kB).
FYI @ArturGaspar @0x29a 
See https://github.com/openedx/frontend-app-learner-dashboard/issues/325 which is the same problem affecting …

fix: don't accidentally bundle paragon CSS x2

---

src/editors/sharedComponents/TinyMceWidget/hooks.js
src/editors/sharedComponents/TinyMceWidget/hooks.test.js

This PR fixes the error of relative asset urls incorrectly rewriting the conversion to the static url.  The regex matcher was catching all relative asset url formats:
- `/assets/courseware/v1/hash/asset-v1:org+num+run+type@asset+block/image.jpeg`
- `/asset-v1:org+num+run+type@asset+block@image.jpeg`
- `/asset-v1:org+num+run+type@asset+block/image.jpeg`
This resulted in the first two version rewriting correctly as `/static/image.jpeg` and the third rewriting incorrectly as `/static/assetblockimage.jpeg`.
1. Open a raw editor
2. Add an image with a static link
3. Save the block
4. Using browser dev tools, copy the link for the image
5. Reopen the block
6. Confirm that the static is unaltered
7. Paste the previously copied image
8. Add images using the second and third bullet points' format …

fix: setAssetToStaticUrl regex matcher

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget/index.scss
src/editors/containers/VideoUploadEditor/index.scss

This PR removes paragon scss variable imports from `.scss` files. These imports break the build of the course authoring MFE because of a `ModuleErrorBuild`. The only variable used is `$gray-500` and the hex code for the variable is the same in the openedX and edX themes, `#707070`, so replacement will have no affect on the UI

fix: remove imports breaking build

---

src/editors/sharedComponents/TinyMceWidget/hooks.js
src/editors/sharedComponents/TinyMceWidget/hooks.test.js
src/editors/sharedComponents/TinyMceWidget/utils.js

This PR fixes images not loading in the visual text and problem editor. When assets were loaded with `asset-v1:org+number+run+type@asset+block/image_name.png` asset format, it would incorrectly parse to `asset-v1:org+number+run+type@asset+block/asset-v1:org+number+run+type@asset+block@image_name.png`. A similar issue was fixed in #497. The same src parser is now used for `replaceStaticWithAsset` as was added for `setAssetToStaticUrl`.
1. Open an html block
2. Add an image
3. Click the "HTML" button in the toolbar
4. Replace the second "@" with "/"
5. Click "Save"
6. Confirm that the image is still visible

fix: asset name parsing in static converter

---

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/hooks.js
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TimerCard.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/Tolerance/index.test.jsx
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap
src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TimerCard.test.jsx.snap

This pull request contains fixes to problem number fields `Scoring point (weight)`, `Scoring attempts`, `Show answer`, `Time between attempts` and `Tolerance`.
According to old (legacy) studio functionality were changed:
- add minimum value limits to all problem number fields
- add ability to enter float number value to `Scoring points (weight)` and `Tolerance` fields

fix: add validation to problem number fields

---

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx
src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap

- The "Share alike" checkbox now works correctly after selecting and saving it.
- The "View license details" link is only displayed for Creative Commons license type.
**Basic setup**
Go to `studio -> unit -> Video block -> scroll to the end of editors page and click on the "Add a license for this video" button`.
1. **"Share alike" issue:**
`basic setup -> in the "License type" field select "Creative Commons" -> Check Share alive (No derivatives unchecked) -> save -> open for edit again`
ACTUAL RESULT: Share Alike option is displayed as unchecked
EXPECTED RESULT: Share Alike option is displayed as checked
2. **"View license details link" issue:**
`basic setup -> in the "License type" field select "All Rights Reserved".`
ACTUAL RESULT: View license details with link to …

fix: license widget checkbox and link

---

src/editors/containers/ProblemEditor/data/OLXParser.js

The regular expression for parsing isAnswerRange has been extended; it accepts the following response forms: `[1,10]`, `[1, 10]`, `[ 1,10 ]`, `[ 1, 10 ]`, `[1, 10 ] `, `[ 1, 10]`.
1) Go to studio -> unit -> problem -> Numerical input - check that Tolerance field is active
2) In Answers block click on "+ Add answer" -> Add answer range - check that Tolerance field became inactive
3) In answer range field fill in for example [1, 10] (space after comma is necessary), save changes
4) Click on Edit for problem.
Tolerance became active, possible in "+ Add answer" click on Add answer
Behaviour should be like when there's no space after comma in range

fix: answer range validation in Numerical input

---

src/editors/data/redux/problem/reducers.js

This pull request contains a fix for an issue where the selected response options (for a single response type - Dropdown) are reset when switching issue types.
During multi-changing problem type and setting correct answers our counter flag `correctAnswerCount` went below zero value, that has been fixed.

fix: reset active answers for single answer problem type

---

src/editors/sharedComponents/TypeaheadDropdown/index.jsx

When using Tab to move from Org field to the
next Course number field the Org value is not saved.
Closes https://github.com/openedx/frontend-app-authoring/issues/1199 for Redwood release.
This fix differs from the one to the [frontend-app-authoring](https://github.com/openedx/frontend-app-authoring/pull/1279) since the value we want to save in DB should be raw (not normalized).
Fixed behavior:
https://github.com/user-attachments/assets/f8d264eb-6232-4cb1-86ac-6cfa1afca245

fix: course creation button is inactive
