openedx/frontend-lib-content-components

src/editors/containers/TextEditor/TextEditor.jsx, src/editors/containers/TextEditor/TextEditor.test.jsx, src/editors/containers/TextEditor/__snapshots__/TextEditor.test.jsx.snap, src/editors/containers/TextEditor/hooks.test.jsx
Imageuploadmodal will be added once imageupload is a real component.
=> test: add TextEditor Tests

jest.config.js, src/editors/containers/TextEditor/TextEditor.jsx, src/editors/containers/TextEditor/TextEditor.test.jsx, src/editors/containers/TextEditor/__snapshots__/TextEditor.test.jsx.snap, src/editors/containers/TextEditor/components/ImageSettingsModal/AltTextControls.jsx, src/editors/containers/TextEditor/components/ImageSettingsModal/AltTextControls.test.jsx, src/editors/containers/TextEditor/components/ImageSettingsModal/DimensionControls.jsx, src/editors/containers/TextEditor/components/ImageSettingsModal/DimensionControls.test.jsx, src/editors/containers/TextEditor/components/ImageSettingsModal/__snapshots__/AltTextControls.test.jsx.snap, src/editors/containers/TextEditor/components/ImageSettingsModal/__snapshots__/DimensionControls.test.jsx.snap, src/editors/containers/TextEditor/components/ImageSettingsModal/__snapshots__/index.test.jsx.snap, src/editors/containers/TextEditor/components/ImageSettingsModal/hooks.js, src/editors/containers/TextEditor/components/ImageSettingsModal/hooks.test.js, src/editors/containers/TextEditor/components/ImageSettingsModal/index.jsx, src/editors/containers/TextEditor/components/ImageSettingsModal/index.scss, src/editors/containers/TextEditor/components/ImageSettingsModal/index.test.jsx, src/editors/containers/TextEditor/components/ImageUploadModal.jsx, src/editors/containers/TextEditor/components/SelectImageModal.jsx, src/editors/data/constants/mockData.js, src/editors/data/services/cms/mockApi.js, src/setupTest.js, www/src/index.jsx
The current dimension lock behavior should be stable, but may not be optimal.  A better user experience would need a solid design though.
=> feat: Image settings feature and design completeness

src/editors/containers/TextEditor/components/ImageSettingsModal/hooks.test.js, src/testUtils.js
Creates a re-usable testUtil out of the useState mock pattern used in the recent hook PR.
Example usage in docstring :-)
```
/**
* Mock utility for working with useState in a hooks module.
* Expects/requires an object containing the state object in order to ensure
* the mock behavior works appropriately.
*
* Expected format:
*   hooks = { state: { <key>: (val) => React.createRef(val), ... } }
*
* Returns a utility for mocking useState and providing access to specific state values
* and setState methods, as well as allowing per-test configuration of useState value returns.
*
* Example usage:
*   // hooks.js
*   import * as module from './hooks';
*   const state = {
*     isOpen: (val) => React.useState(val),
*     hasDoors: (val) => React.useState(val),
*     selected: (val) => …
```
=> feat: useState test util

package-lock.json, src/editors/components/EditorFooter/__snapshots__/index.test.jsx.snap, src/editors/components/EditorFooter/index.jsx
=> fix: text editor save

src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap, src/editors/containers/EditorContainer/index.jsx, src/editors/containers/EditorContainer/index.test.jsx
[TNL-9882 "Disabled Save button" Feedback on ImageSettings form is not sufficient] https://openedx.atlassian.net/browse/TNL-9882)
=> feat: The X Button in the Top Right Doesn't do anything.

docs/decisions/0002-text-editor-adr.md
Mostly how to use and extended tinyMCE
=> docs: ADR for text editor decisions May 2022

src/editors/containers/TextEditor/__snapshots__/index.test.jsx.snap, src/editors/containers/TextEditor/hooks.js, src/editors/containers/TextEditor/hooks.test.jsx, src/editors/containers/TextEditor/index.jsx, src/editors/containers/TextEditor/index.test.jsx, src/editors/containers/TextEditor/pluginConfig.js, src/editors/data/constants/tinyMCE.js
adresses
https://2u-internal.atlassian.net/browse/TNL-9836
and 
https://2u-internal.atlassian.net/browse/TNL-9936
=> feat: add simple code block and blockquote buttons

src/editors/containers/TextEditor/pluginConfig.js
https://2u-internal.atlassian.net/browse/TNL-9940
Solution was a simple change to tinyMCE config for 'toolbar_sticky' to be true.
=> feat: toolbar stays visible when scrolling

README.md
This updates the Readme of the project
~~**Discussions**: Link to any public dicussions about this PR or the design/architecture. Otherwise omit this.~~
**Dependencies**: None
**Screenshots**: Always include screenshots if there is any change to the UI.
~~**Sandbox URL**: TBD - sandbox is being provisioned.~~
**Merge deadline**: "None" 
**Testing instructions**:
None
**Author notes and concerns**:
None
**Reviewers**
Fixes: <>
Co-authored-by: <>
Private-ref: Part of https://tasks.opencraft.com/browse/BB-6582
=> chore: Update the Readme for project

src/editors/containers/TextEditor/hooks.js, src/editors/containers/TextEditor/pluginConfig.js
This PR adds the `document_base_url` for tinyMCE. This allows relative URLS to be seen.
JIRA Ticket: [TNL-10063](https://2u-internal.atlassian.net/browse/TNL-10063)
=> feat: allow relative urls for assets

src/editors/data/redux/thunkActions/video.js, src/editors/data/redux/thunkActions/video.test.js, src/editors/data/services/cms/mockApi.js
https://2u-internal.atlassian.net/browse/TNL-10009
This change loads data from blockValue to the video redux store.
=> Convert video settings from xblock metadata into the redux store. In-progress draft. TNL-10009.

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/DurationWidget.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/duration.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/duration.test.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/handlers.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/handlers.test.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/hooks.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/hooks.test.js
https://2u-internal.atlassian.net/browse/TNL-10201
Bonus features on feedback from Jon:
1. limit the number of numbers to 6
2. automatically insert the colon ( : ) symbols while typing
3. only allow the user to enter numbers (no letters or other symbols)
4. In legacy it saves the users entry when the return key is pressed, we could add that.
=> feat: duration entree addtional features

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap
Solves: https://2u-internal.atlassian.net/browse/TNL-10243 
spacing now like this:
=> feat: increase spacing between video settings

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/HandoutWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseBlurb.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseBlurb.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDetails.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseSelector.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/messages.js, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/DurationWidget.test.jsx.snap
JIRA Tickets: [](https://2u-internal.atlassian.net/browse/TNL-10249) and [TNL-10250](https://2u-internal.atlassian.net/browse/TNL-10250)
This PR fixes font size issues, row alignment issues, wrong tooltip text, and misused card styling.
=> fix: license styling

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/DurationWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDisplay.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDetails.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDisplay.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseSelector.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/DurationWidget.test.jsx.snap
JIRA Ticket: [TNL-10245](https://2u-internal.atlassian.net/browse/TNL-10245)
This PR fixes the spacing between all items. Each widget and divider have a padding of 24 px. All items within a widget have a padding of 16 px. Checkbox groups  have a top padding of 32 px.
=> fix: vertical spacing between items

src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseDetails.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseDetails.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/__snapshots__/LicenseSelector.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/LanguageSelector.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/Transcript.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/LanguageSelector.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/__snapshots__/Transcript.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/CollapsibleFormWidget.test.jsx.snap
JIRA Ticket: [TNL-10244](https://2u-internal.atlassian.net/browse/TNL-10244)
This PR fixes all the left alignments of the `form.controls` and widget headers. Icons (delete, collapse, checkboxes) are properly left aligned.
=> fix: left and right alignment

package-lock.json, package.json, src/editors/containers/VideoEditor/components/VideoSettingsModal/ErrorSummary.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/CollapsibleFormWidget.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/LicenseWidget/LicenseSelector.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/ThumbnailWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/Transcript.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/TranscriptWidget/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/VideoSourceWidget/index.jsx, src/editors/sharedComponents/ErrorAlerts/ErrorAlert.jsx
Solves: https://2u-internal.atlassian.net/browse/TNL-10239
=> feat: make delete and info icons outlines

src/editors/Editor.test.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeCard.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.test.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/SelectTypeFooter.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.test.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/messages.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.test.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/ProblemTypeSelect.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/index.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/index.test.jsx, src/editors/data/constants/problem.js, src/editors/data/redux/problem/reducers.js, src/editors/data/redux/thunkActions/app.test.js, src/editors/data/redux/thunkActions/problem.js, src/editors/data/services/cms/mockApi.js
https://2u-internal.atlassian.net/browse/TNL-10191
This change sets up the problem type selection page on the Problem Editor.
=> feat: problem type selection

src/editors/containers/ProblemEditor/hooks.js
JIRA Tickets: [TNL-10330](https://2u-internal.atlassian.net/browse/TNL-10330), [TNL-10325](https://2u-internal.atlassian.net/browse/TNL-10325)
This PR address the console.log errors from the question box tinyMCE, removing the tinyMCE branding and menu.
=> fix: remove question box branding + menu

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/HintRow.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeCard.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/index.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/messages.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/AdvanceTypeSelect.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/AdvanceTypeSelect.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/Preview.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/ProblemTypeSelect.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/messages.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/index.jsx, src/editors/containers/VideoEditor/components/VideoSettingsModal/components/__snapshots__/DurationWidget.test.jsx.snap, src/editors/data/constants/problem.js, src/setupTest.js
JIRA Tickets: [TNL-10331](https://2u-internal.atlassian.net/browse/TNL-10331), [TNL-10315](https://2u-internal.atlassian.net/browse/TNL-10315)
=> feat: update problem type titles + small ui fixes

src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.js, src/editors/containers/ProblemEditor/components/SelectTypeModal/hooks.test.js
https://2u-internal.atlassian.net/browse/TNL-10334
Choosing a simple problem type lands you in editor with the accurate default problem title.
=> fix: update title on type select

package-lock.json, package.json, src/colors.scss, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswersContainer.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/index.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/FeedbackBox.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Feedback/__snapshots__/FeedbackBox.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/index.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/index.scss, www/package-lock.json, www/package.json
JIRA Ticket: [TNL-10338](https://2u-internal.atlassian.net/browse/TNL-10338)
=> feat: change feedback and delete icons to outline variants

src/editors/containers/ProblemEditor/data/OLXParser.js, src/editors/containers/ProblemEditor/data/mockData/olxTestData.js, src/editors/data/constants/basicOlxTemplates/dropdown.js, src/editors/data/constants/basicOlxTemplates/multiSelect.js, src/editors/data/constants/basicOlxTemplates/numeric.js, src/editors/data/constants/basicOlxTemplates/singleSelect.js, src/editors/data/constants/basicOlxTemplates/textInput.js
JIRA Ticket: [TNL-10344](https://2u-internal.atlassian.net/browse/TNL-10344)
This PR changes the default text for questions and updates the `<bold>` tag to `<strong>` so that it is correctly rendered by tinyMCE.
=> feat: change default question text

src/editors/Editor.jsx, src/editors/__snapshots__/Editor.test.jsx.snap, src/editors/containers/EditorContainer/__snapshots__/index.test.jsx.snap, src/editors/containers/EditorContainer/components/EditorFooter/__snapshots__/index.test.jsx.snap, src/editors/containers/EditorContainer/components/EditorFooter/index.jsx, src/editors/containers/EditorContainer/index.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/SelectTypeFooter.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/SelectTypeWrapper/__snapshots__/SelectTypeFooter.test.jsx.snap, src/editors/sharedComponents/RawEditor/__snapshots__/index.test.jsx.snap, src/editors/sharedComponents/RawEditor/index.jsx
JIRA Ticket: [TNL-10343](https://2u-internal.atlassian.net/browse/TNL-10343)
While testing check all editors to make sure the footer does not block any content.
=> feat: change editor footer from sticky to fixed

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/HintsCard.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ScoringCard.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/TypeCard.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/HintsCard.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/ScoringCard.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/TypeCard.test.jsx.snap, src/editors/containers/ProblemEditor/data/SettingsParser.js, src/editors/containers/ProblemEditor/data/SettingsParser.test.js, src/editors/containers/ProblemEditor/data/mockData/problemTestData.js, src/editors/data/redux/problem/reducers.js
fix: Correct summary of number of attempts; new separator between attempts summary and points summary; hint text for both attempts and points settings; fixed some widget paddings; advanced problems do not show type setting, and type setting menu does not show advanced problems. TNL-10332.
=> fix: various style and UX fixes. TNL-10332.

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/index.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/messages.js, src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/Preview.test.jsx.snap, src/editors/data/constants/problem.js
JIRA Ticket: [TNL-10378](https://2u-internal.atlassian.net/browse/TNL-10378)
This PR updates the strings (helper text) that guide users on inputing answers choices.
=> feat: update answer helper text

src/editors/containers/ProblemEditor/data/OLXParser.js, src/editors/containers/ProblemEditor/data/OLXParser.test.js, src/editors/containers/ProblemEditor/data/mockData/olxTestData.js, src/editors/containers/ProblemEditor/hooks.js, src/editors/data/constants/basicOlxTemplates/dropdown.js, src/editors/data/constants/basicOlxTemplates/multiSelect.js, src/editors/data/constants/basicOlxTemplates/numeric.js, src/editors/data/constants/basicOlxTemplates/singleSelect.js, src/editors/data/constants/basicOlxTemplates/textInput.js, src/editors/data/constants/tinyMCEStyles.js
fix: question field uses real placeholder instead of template. fixed blank question handling. TNL-10395, TNL-10411.
=> fix: question field uses real placeholder instead of template. fixed blank question handling. TNL-10395, TNL-10411.

src/editors/data/constants/tinyMCEStyles.js
fix: correct css for text margins in question tinymce. TNL-10390.
=> fix: correct css for text margins in question tinymce. TNL-10390.

src/editors/containers/ProblemEditor/data/OLXParser.js, src/editors/containers/ProblemEditor/data/OLXParser.test.js, src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
fix: correct question parsing/building after use of styling. TNL-10413.
=> fix: correct question parsing/building after use of styling. TNL-10413.

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/components/Checker/index.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/index.scss
This PR makes the radio and checkboxes in problem editor green when checked. This is intended to override paragon.
https://2u-internal.atlassian.net/browse/TNL-10376
=> feat: make radio and checkbox green

src/editors/containers/ProblemEditor/components/SelectTypeModal/content/Preview.jsx, src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/Preview.test.jsx.snap, src/editors/data/constants/problem.js
The text that was rendered in the problem preview was the text for the answer description. Now the text matches the expected problem description found in the mocks.
=> fix: update problem description in preview block

src/editors/containers/ProblemEditor/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/index.jsx, src/editors/containers/ProblemEditor/index.test.jsx, src/editors/containers/ProblemEditor/messages.js
fix: ProblemEditor useEffect at beginning of component; message for block failed to load. TNL-10507
=> fix: ProblemEditor useEffect at beginning of component; message for block failed to load. TNL-10507

.tx/config, Makefile, package-lock.json, package.json
**Ticket**
[Updating /api/v2 transifex endpoints](https://github.com/edx/edx-arch-experiments/issues/202)
**What has changed?**
- Update Makefile commands for new v3 transifex API
- Add edx/reactifex as dependency
**Reference PR**
https://github.com/openedx/frontend-app-learning/pull/837
=> Update transifex api from v2 to v3

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
To match how the OLX currently works, this PR removes general feedback and group feedback for problem types except for multi-select.
https://2u-internal.atlassian.net/browse/TNL-10523
=> feat: remove general and group feedback

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/ShowAnswerCard.jsx
added a margin to meet requirements. it is 4 not three to handle the floating label on the input.
=> fix: show answer attempts spacing

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/messages.js, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/SwitchToAdvancedEditorCard.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/settingsComponents/__snapshots__/SwitchToAdvancedEditorCard.test.jsx.snap
Reverts openedx/frontend-lib-content-components#259
=> Revert "feat: update switch to Advanced Editor warning"

src/editors/sharedComponents/ErrorBoundary/ErrorPage.jsx, src/editors/sharedComponents/ErrorBoundary/index.test.jsx, src/editors/sharedComponents/ErrorBoundary/messages.js
fix: ErrorPage rewritten as functional component with injected i18n. TNL-10535
=> fix: ErrorPage rewritten as functional component with injected i18n. TNL-10535

src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswerOption.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/AnswersContainer.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswerOption.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/AnswerWidget/__snapshots__/AnswersContainer.test.jsx.snap, src/editors/containers/ProblemEditor/data/ReactStateOLXParser.js, src/editors/containers/ProblemEditor/data/ReactStateOLXParser.test.js, src/editors/containers/ProblemEditor/data/mockData/editorTestData.js, src/editors/containers/ProblemEditor/data/mockData/olxTestData.js, src/editors/data/services/cms/api.js
JIRA Ticket: [TNL-10311](https://2u-internal.atlassian.net/browse/TNL-10311)
This PR adds a check to see if a numerical response's answer range is a valid format ([smaller, larger]). Currently any order is valid for an answer range, such as (larger, smaller]. We need to enforce the expected format to guarantee answers are graded properly.
=> feat: add check to sanitize answer ranges

src/editors/containers/ProblemEditor/data/OLXParser.js, src/editors/containers/ProblemEditor/data/OLXParser.test.js, src/editors/containers/ProblemEditor/data/mockData/olxTestData.js
Solves the CAT-2 bug where content was lost as it was not being parsed by the inbound parser.
Testing instructions:
Created an advanced problem with the following OLX:
```
<problem>
<p style="text-align: center;"><img height="274" width="" src="/static/boiling_eggs_water_system.png" alt="boiling eggs: water system"/></p>
<multiplechoiceresponse>
<label>Taking the system as just the <b>water</b>, as indicated by the red dashed line, what would be the correct expression for the first law of thermodynamics applied to this system?</label>
<choicegroup type="MultipleChoice">
<choice correct="false">( \Delta E_\text{eggs} = Q - W )</choice>
<choice correct="false">( \Delta E_\text{eggs} = Q )</choice>
<choice correct="false">( \Delta E_\text{eggs} = - W )</choice>
<choice correct="false">( …
```
=> fix: parse description/label as children

src/editors/containers/ProblemEditor/data/OLXParser.js
Follow on:
this creates the ability for explanations to work if they are:
1. Not a child of a response type
2. Use an h2 tag for the explanation title
3. do not use the "Explanation" title.
This is all because we have very "open" ways of rendering olx.
=> fear: parse solution as siblings

src/editors/containers/ProblemEditor/data/OLXParser.js
We need these lines of code to be more typesafe. Underscore allows us to give falsy values if our get fails, instead of erroring.
Note: i will squash for commitlint.
=> Feat  parse solution as sibling

src/editors/containers/ProblemEditor/components/EditProblemView/SettingsWidget/index.jsx
This PR displays the Show reset settings widget for advanced problem editor.
=> feat: show reset for advanced problem editor

src/editors/containers/ProblemEditor/components/EditProblemView/__snapshots__/index.test.jsx.snap, src/editors/containers/ProblemEditor/components/EditProblemView/hooks.js, src/editors/containers/ProblemEditor/components/EditProblemView/hooks.test.js, src/editors/containers/ProblemEditor/components/EditProblemView/index.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/index.test.jsx, src/editors/containers/ProblemEditor/components/EditProblemView/messages.js, src/editors/hooks.js, src/editors/hooks.test.jsx
JIRA Ticket: [TNL-10312](https://2u-internal.atlassian.net/browse/TNL-10312)
This PR adds a confirmation alert when a problem does not have a correct answer selected or the correct answer selected has no title. When the user clicks save an alert will appear and if the user confirms the save, the problem will save. Otherwise the alert will disappear and the user will be able to edit the problem.
=> feat: add no answer confirmation alert

src/editors/EditorPage.jsx, src/editors/EditorPage.test.jsx, src/editors/VideoSelectorPage.jsx, src/editors/VideoSelectorPage.test.jsx, src/editors/__snapshots__/EditorPage.test.jsx.snap, src/editors/__snapshots__/VideoSelectorPage.test.jsx.snap, src/editors/containers/ProblemEditor/index.jsx, src/editors/sharedComponents/ErrorBoundary/ErrorPage.jsx, src/editors/sharedComponents/ErrorBoundary/ErrorPage.test.jsx, src/editors/sharedComponents/ErrorBoundary/__snapshots__/ErrorPage.test.jsx.snap, src/editors/sharedComponents/ErrorBoundary/index.jsx, src/editors/sharedComponents/ErrorBoundary/index.test.jsx, src/editors/sharedComponents/ErrorBoundary/messages.js
JIRA Ticket: [TNL-10387](https://2u-internal.atlassian.net/browse/TNL-10387)
=> feat: add a button to return to studio

docs/decisions/0006-test-names.rst
I added a PR for some test naming conventions that I feel are useful for us. It's a small ADR. Would be great to get some feedback!
=> docs: add adr with test naming conventions

package-lock.json, package.json, src/editors/sharedComponents/ErrorBoundary/index.test.jsx, src/setupTest.js
chore: update react to 17, etc. TNL-10715
=> chore: update react to 17, etc. TNL-10715

package-lock.json, package.json, src/editors/sharedComponents/ErrorBoundary/index.test.jsx, src/setupTest.js
Reverts openedx/frontend-lib-content-components#338
=> Revert "chore: update react to 17, etc. TNL-10715"

package-lock.json, src/editors/data/services/cms/urls.js, src/editors/data/services/cms/urls.test.js
feat: v2 xblocks should use v2 url. TNL-10742
=> feat: v2 xblocks should use v2 url. TNL-10742

.github/workflows/lockfileversion-check.yml
=> chore: update lock version file

src/editors/containers/GameEditor/index.jsx, src/editors/data/constants/app.js, src/editors/data/redux/game/index.js, src/editors/data/redux/game/reducers.js, src/editors/data/redux/game/selectors.js, src/editors/data/redux/index.js, src/editors/data/services/cms/mockApi.js, src/editors/supportedEditors.js
Preliminary code for game editor. An empty index.jsx file along with empty react state is set up. The gallery view is set up to select the game editor.
1. Run gallery view by `cd`'ing into the `www` folder and running `npm start`.
2. Click the `game` radio button to see the game editor.
3. It should say hello world.
Note: test code to be added in a future PR.
=> feat: setup game editor work

src/editors/containers/EditorContainer/hooks.js, src/editors/data/services/cms/api.js, src/editors/data/services/cms/urls.js, src/editors/data/services/cms/urls.test.js
feat: more/correct v2 url handling. TNL-10742
=> feat: more/correct v2 url handling. TNL-10742

src/editors/data/services/cms/urls.js, src/editors/data/services/cms/urls.test.js
1. Go to link in studio
2. Click “edit” next to text component.
3. expect the page to load
=> fix: error return while editor loading

package-lock.json, package.json, src/editors/sharedComponents/TypeaheadDropdown/FormGroup.jsx, src/editors/sharedComponents/TypeaheadDropdown/FormGroup.test.jsx, src/editors/sharedComponents/TypeaheadDropdown/index.jsx, src/editors/sharedComponents/TypeaheadDropdown/index.test.jsx, src/index.jsx
JIRA Ticket: [TNL-10593](https://2u-internal.atlassian.net/browse/TNL-10593)
Test this PR using frontend-app-library-authoring [PR #269](https://github.com/openedx/frontend-app-library-authoring/pull/269)
=> feat: add typeahead component

src/editors/data/services/cms/api.js, src/editors/data/services/cms/api.test.js
fix: don't even bother fetching block ancestor in v2.
=> fix: don't even bother fetching block ancestor in v2.

src/editors/data/services/cms/api.js, src/editors/data/services/cms/api.test.js, src/editors/data/services/cms/urls.js, src/editors/data/services/cms/urls.test.js
fix: revert to blank-url version of error handling, for now
=> fix: revert to blank-url version of error handling, for now

src/editors/data/redux/app/selectors.js, src/editors/data/redux/app/selectors.test.js, src/editors/data/services/cms/urls.js, src/editors/data/services/cms/urls.test.js
fix: don't get returnUrl for v2 blocks.
=> fix: don't get returnUrl for v2 blocks.

README.md, example/jest.config.example.js, example/setupTest.example.js
This is a documentation addition, since the last time we included this library in a new project, the jest pipeline failed. This documents what is necessary to fix that.
https://2u-internal.atlassian.net/browse/TNL-10927
=> docs: document jest troubleshooting

src/editors/containers/ProblemEditor/components/SelectTypeModal/content/__snapshots__/AdvanceTypeSelect.test.jsx.snap, src/editors/data/constants/problem.js
JIRA Ticket: [TNL-11009](https://2u-internal.atlassian.net/browse/TNL-11009)
> “Advanced” should be removed from the title of newly added problems
This PR relates to  `edx-platform` PR # [33240](https://github.com/openedx/edx-platform/pull/33240)
=> fix: name of blank problems

src/editors/data/constants/tinyMCE.js, src/editors/sharedComponents/TinyMceWidget/hooks.js, src/editors/sharedComponents/TinyMceWidget/pluginConfig.js, src/setupTest.js
fix: misssing part of paid plugin configuration
=> fix: misssing part of paid plugin configuration

src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
fix: disable paid plugins, to test prod issue in stage
=> fix: disable paid plugins, to test prod issue in stage

src/editors/data/services/cms/api.js, src/editors/data/services/cms/api.test.js
Reverts openedx/frontend-lib-content-components#431
=> Revert "fix: get library blocks editing to work locally"

src/editors/sharedComponents/TinyMceWidget/pluginConfig.js
Reverts openedx/frontend-lib-content-components#432
=> Revert "fix: disable paid plugins, to test prod issue in stage"

package-lock.json, package.json
fix: update public plugins repo version
=> fix: update public plugins repo version

src/editors/containers/ProblemEditor/components/SelectTypeModal/content/ProblemTypeSelect.jsx, src/editors/sharedComponents/SelectionModal/Gallery.jsx, src/editors/sharedComponents/SelectionModal/GalleryCard.jsx
Mainly to trigger an npm release.
=> fix: gallery

.github/pull_request_template.md, README.md
@KristinAoki As you suggested, this PR adds a notice to the README (and the PR template) that we're in the process of moving this repo.
=> docs: note that this repo is being moved

README.md
Before we archive this, I'll update the notice in the README.
=> chore: update README to note that this has been moved.

README.md
some docs updates, but with a feat! commit
so that it triggers a release and pushes
our "Moved" message to NPM
=> feat!: this repo is unsupported
